EXEC=gpuDP
GRIDLINES=no
VERBOSE=no
DEBUG=no
SRC=src/main.cu
TGT=bin/$(EXEC)
TMP=*~ $(TGT)
BSX=32
BSY=32
BENCHMARK=no
REPEATS=32
REALIZATIONS=10
ARCH=sm_86
DP_RDC=-rdc=true -DRDC_TRUE -lcudadevrt -lnvidia-ml
DP_PENDING_KERNEL_BUFFER=$$((1024*512))
MEASURE_POWER := MEASURE_POWER

build:
	nvcc -O3 -arch=${ARCH} ${DP_RDC} -Xcompiler -fopenmp -lpng -DARCH=$(ARCH) -D${VERBOSE} -D${MEASURE_POWER} -D${GRIDLINES} -D${DEBUG} -D${BENCHMARK} -DBSX=$(BSX) -DBSY=$(BSY) -DREALIZATIONS=${REALIZATIONS} -DREPEATS=$(REPEATS) -DDP_PENDING_KERNEL_BUFFER=${DP_PENDING_KERNEL_BUFFER} -c src/nvmlPower.cu -o obj/nvmlPower.o
	nvcc -O3 -arch=${ARCH} ${DP_RDC} -Xcompiler -fopenmp -lpng -DARCH=$(ARCH) -D${VERBOSE} -D${MEASURE_POWER} -D${GRIDLINES} -D${DEBUG} -D${BENCHMARK} -DBSX=$(BSX) -DBSY=$(BSY) -DREALIZATIONS=${REALIZATIONS} -DREPEATS=$(REPEATS) -DDP_PENDING_KERNEL_BUFFER=${DP_PENDING_KERNEL_BUFFER} -c $(SRC) -o obj/main.o
	nvcc -O3 -arch=${ARCH} ${DP_RDC} -Xcompiler -fopenmp -lpng -DARCH=$(ARCH) -D${VERBOSE} -D${MEASURE_POWER} -D${GRIDLINES} -D${DEBUG} -D${BENCHMARK} -DBSX=$(BSX) -DBSY=$(BSY) -DREALIZATIONS=${REALIZATIONS} -DREPEATS=$(REPEATS) -DDP_PENDING_KERNEL_BUFFER=${DP_PENDING_KERNEL_BUFFER} obj/nvmlPower.o obj/main.o -o $(TGT)

run: $(TGT)
	./$(TGT)

clean:
	rm -f $(TMP)
